#pragma once

enum ComponentIndex {
	CAMERA,
	COLLIDE,
	CONTROL_BALL,
	CONTROL_BRICK,
	CONTROL_PADDLE,
	DRAW2D,
	MOVE,
	RENDER,
	TRANSFORM2D,
};

enum ComponentMask {
	HAS_CAMERA = 1 << CAMERA,
	HAS_COLLIDE = 1 << COLLIDE,
	HAS_CONTROL_BALL = 1 << CONTROL_BALL,
	HAS_CONTROL_BRICK = 1 << CONTROL_BRICK,
	HAS_CONTROL_PADDLE = 1 << CONTROL_PADDLE,
	HAS_DRAW2D = 1 << DRAW2D,
	HAS_MOVE = 1 << MOVE,
	HAS_RENDER = 1 << RENDER,
	HAS_TRANSFORM2D = 1 << TRANSFORM2D,
};
